// <auto-generated />
namespace BankingApp.L0.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreationInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreationInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201810311107315_Creation Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
